[font]
normal = ["CaskaydiaCove Nerd Font", "Sarasa Mono SC Nerd Font"]
size = 14

[font.features]
# simple compiler & simulator
# -> => != <> >= 0 1 2 3
"CaskaydiaCove Nerd Font" = ["+ss01", "+ss02", "+ss04", "+ss05", "+ss06", "+zero", "+onum"]
